export const OPERATION_NAMES = [
  "catalog.list",
  "connector.list",
  "connector.inspect",
  "capture.ingest",
  "capture.connection.list",
  "capture.connection.create",
  "capture.connection.check",
  "capture.connection.discover",
  "capture.connection.activate",
  "capture.connection.update",
  "capture.connection.pause",
  "capture.connection.run",
  "capture.dlq.list",
  "capture.dlq.replay",
  "view.get",
  "view.resolve.latest",
  "view.query",
  "view.graph.project",
  "view.search",
  "view.search.reindex",
  "view.traverse",
  "view.tombstone",
  "view.authoring.request",
  "view.authoring.propose",
  "view.authoring.inspect",
  "view.authoring.approve",
  "view.authoring.reject",
  "view.authoring.apply",
  "transformation.submit",
  "transformation.get",
  "run.execute",
  "run.inspect",
  "run.cancel",
  "feedback.submit",
  "feedback.apply",
  "failure.inspect",
  "policy.decision.get",
  "privacy.forget.request",
  "privacy.forget.execute",
  "privacy.forget.inspect",
  "trace.read",
] as const;

export type OperationName = typeof OPERATION_NAMES[number];
